### ISSUE TITLE
TOMU detects as "ComNav GNSS receiver" on Windows 10

### ISSUE THREAD

**Issue by hamsternz** [im-tomu/tomu-bootloader#23] opened 2018-02-01 09:47 UTC
Fixing the "ComNav GNSS Receiver" issue

I've had two laptops where the TOMU detected as a "ComNav GNSS Receiver" and would not act as a virtual COM port.

This resolved the issue for me.

1. Leave the TOMU from your USB port

2. Start a CMD prompt, but ensure you run it as administrator. (Press Windows Key, type "cmd", right-click on "Command Prompt" and select "Run as Administrator")

3. In the command prompt, type the following to start device manager with special settings:
     set DEVMGR_SHOW_NONPRESENT_DEVICES=1
     devmgmt.msc

4. From the "view" menu, select "Show hidden Devices"

5. Navigate to "Universal Serial Bus controller", and expand it.

6. Right-click on the "ComNav GNSS Receiver" item and choose properties

7. Go to the "Driver panel", and click on the "Uninstall driver" button

8. Make sure you click the "Delete the driver software for this device" checkbox, then click "Uninstall"

9. From the "Actions" menu, choose "Rescan hardware". Your TOMU, and it should now detect as a "USB Serial Device (COMx)" device, under "Ports (COM & LPT)"

**Comment by xobs** [comment] 2018-02-02 02:16
This is expected behavior, and was part of the motivation for moving to a DFU bootloader.

I agree that it's not very intuitive, and while the main page does have a link to https://www.m-pression.com/solutions/boards/odyssey/odyssey-downloads which contains the SiLabs drivers, it's not clear that one needs to download those drivers in order to get it to work.  Additionally, since I'm not sure of what the license is on the SiLabs drivers, I don't really want to distribute them here.

Do you have a suggestion for how to inform people about this issue when using the older CDC bootloader?

**Comment by xobs** [comment] 2018-02-28 07:55
The dfu bootloader no longer shows up as a GPS device.

**Closed as completed by xobs** 2018-02-28 07:55 UTC
